### ISSUE TITLE
Let's make this repo to be the easiest way to run a ding-dong-bot.go bot!

### ISSUE THREAD

**Issue by huan** [wechaty/go-wechaty-getting-started#1]
This repository is for any Go developers who want to build a chatbot based on our great Go Wechaty library.

It will be a great help for all Go developers if we can make this repository to be able to ready for use by running:

1. `git clone`
1. `make install`
1. `make bot`

Then everything will be set up.

I have set up the skeleton of this repo, with the `examples/ding-dong-bot.go`, let's finish this repo so that it can be run out-of-the-box! @wechaty/go  

Related to: https://github.com/wechaty/wechaty/issues/1927

**Comment by dchaofei** [comment]
done!

**Comment by huan** [comment]
Awesome! 

I'll try the Go version later by running this repository.

Thank you very for the efforts of makeing this easy for other go developers!

**Comment by huan** [comment]
I have just tried to run this repo, and it works like a charm!

@dchaofei You are the best super Go guy that I have ever known!
