### ISSUE TITLE
Support to use `WECHATY_PUPPET_HOSTIE_TOKEN` to set Token

### ISSUE THREAD

**Issue by huan** [wechaty/go-wechaty-getting-started#2]
Currently, we are using a hardcoded `Token` in our ding-dong-bot.go to specify the hostie token.

It would be better to let the user be able to use the environment variable to archive the same goal.

I'd like to suggest that we can add this support to this project so that the user can use the following shell command to start the bot:

```sh
WECHATY_PUPPET_HOSTIE_TOKEN=xxx make bot
```

**Comment by dingdayu** [comment]
This feature is already supported, so close.

https://github.com/wechaty/go-wechaty/pull/51
