### ISSUE TITLE
无法启动

### ISSUE THREAD

**Issue by echoboss** [wechaty/go-wechaty-getting-started#7]
### 获取不到endpoint

> [root@macro go-wechaty-getting-started]# WECHATY_PUPPET_HOSTIE_TOKEN=puppet_padplus_xxxxx go run examples/ding-dong-bot.go
2020/07/01 18:09:45 PuppetHostie Start()
2020/07/01 18:09:46 puppet start err:  PuppetHostie Start() rejection: no endpoint
panic: PuppetHostie Start() rejection: no endpoint
goroutine 1 [running]:
main.main()
        /tmp/go-wechaty-getting-started/examples/ding-dong-bot.go:45 +0x212
exit status 2

**Comment by dingdayu** [comment]
@echoboss 由于你的 Token 是 PadPlus 协议的，暂时未完成 Hostie，需要使用 Dont 协议的 Token 才行。

另外，请注意你的 Token 保密，建议你重置这个 Token.

**Comment by huan** [comment]
See also: https://github.com/wechaty/wechaty/issues/1985

**Comment by echoboss** [comment]
@dingdayu  emit message message.Ready() err: rpc error: code = Internal desc = Assertion failed 无法接受到消息。

**Comment by dingdayu** [comment]
@echoboss 如果可以的请补充更详细的信息，我无法直接确认这个提示出现的地方和原因。

**Comment by echoboss** [comment]
@dingdayu 

### 大概这样子的
➜  go-wechaty git:(master) ✗ go run examples/ding-dong-bot.go
Token:  puppet_padplus_******
Endpoint:
2020/07/02 17:53:12 PuppetHostie Start()
2020/07/02 17:53:13 PuppetHostie onGrpcStreamEvent({type:EVENT_TYPE_SCAN payload:{"qrcode":"http://weixin.qq.com/x/oaBwN7Wob8ZcDVPmqTNT","status":2}})
Scan QR Code to login: ScanStatusWaiting
https://api.qrserver.com/v1/create-qr-code/?data=http://weixin.qq.com/x/oaB*****
2020/07/02 17:53:15 PuppetHostie onGrpcStreamEvent({type:EVENT_TYPE_SCAN payload:{"qrcode":"http://weixin.qq.com/x/4ehEd3Abadl-muq4DQeJ","status":2}})
Scan QR Code to login: ScanStatusWaiting
https://api.qrserver.com/v1/create-qr-code/?data=http://weixin.qq.com/x/oaB*****
2020/07/02 17:53:15 PuppetHostie onGrpcStreamEvent({type:EVENT_TYPE_SCAN payload:{"qrcode":"http://weixin.qq.com/x/4ehEd3Abadl-muq4DQeJ","status":2}})
Scan QR Code to login: ScanStatusWaiting
https://api.qrserver.com/v1/create-qr-code/?data=http://weixin.qq.com/x/oaB*****
2020/07/02 17:53:44 PuppetHostie onGrpcStreamEvent({type:EVENT_TYPE_HEARTBEAT payload:{"data":"66cbf343-ab2e-461d-9fb9-c7724ed6e71c","timeout":60000}})
2020/07/02 17:53:44 PuppetHostie onGrpcStreamEvent({type:EVENT_TYPE_HEARTBEAT payload:{"data":"66cbf343-ab2e-461d-9fb9-c7724ed6e71c","timeout":60000}})
2020/07/02 17:53:49 PuppetHostie onGrpcStreamEvent({type:EVENT_TYPE_SCAN payload:{"qrcode":"","status":3}})
2020/07/02 17:53:49 PuppetHostie onGrpcStreamEvent({type:EVENT_TYPE_SCAN payload:{"qrcode":"","status":3}})
Scan QR Code to login: ScanStatusScanned
https://api.qrserver.com/v1/create-qr-code/?data=
Scan QR Code to login: ScanStatusScanned
https://api.qrserver.com/v1/create-qr-code/?data=
2020/07/02 17:53:54 PuppetHostie onGrpcStreamEvent({type:EVENT_TYPE_SCAN payload:{"qrcode":"","status":4}})
2020/07/02 17:53:54 PuppetHostie onGrpcStreamEvent({type:EVENT_TYPE_SCAN payload:{"qrcode":"","status":4}})
Scan QR Code to login: ScanStatusConfirmed
https://api.qrserver.com/v1/create-qr-code/?data=
Scan QR Code to login: ScanStatusConfirmed
https://api.qrserver.com/v1/create-qr-code/?data=
2020/07/02 17:54:00 PuppetHostie onGrpcStreamEvent({type:EVENT_TYPE_HEARTBEAT payload:{"data":"","timeout":60000}})
2020/07/02 17:54:00 PuppetHostie onGrpcStreamEvent({type:EVENT_TYPE_HEARTBEAT payload:{"data":"","timeout":60000}})
2020/07/02 17:54:00 PuppetHostie onGrpcStreamEvent({type:EVENT_TYPE_LOGIN payload:{"contactId":"wxid_ymd4vsujsr2522"}})
2020/07/02 17:54:00 PuppetHostie ContactRawPayload(wxid_ym******)
User ***** logined
2020/07/02 17:54:22 PuppetHostie onGrpcStreamEvent({type:EVENT_TYPE_HEARTBEAT payload:{"data":"","timeout":60000}})
2020/07/02 17:54:22 PuppetHostie onGrpcStreamEvent({type:EVENT_TYPE_MESSAGE payload:{"messageId":"8542867027116486076"}})
2020/07/02 17:54:22 PuppetHostie onGrpcStreamEvent({type:EVENT_TYPE_HEARTBEAT payload:{"data":"","timeout":60000}})
2020/07/02 17:54:22 PuppetHostie MessagePayload(8542867027116486076)
2020/07/02 17:54:22 PuppetHostie onGrpcStreamEvent({type:EVENT_TYPE_MESSAGE payload:{"messageId":"8542867027116486076"}})
2020/07/02 17:54:22 PuppetHostie MessagePayload(8542867027116486076)
2020/07/02 17:54:22 emit message message.Ready() err: rpc error: code = Internal desc = Assertion failed
2020/07/02 17:54:22 emit message message.Ready() err: rpc error: code = Internal desc = Assertion failed

**Comment by dchaofei** [comment]
@echoboss 你是用 huan 提供的 docker 自己搭建的 token server 吗？我看到 #1985 里有人遇到和你相同的问题

**Comment by echoboss** [comment]
@dchaofei 是的该怎么解决呢？

**Comment by dchaofei** [comment]
> @echoboss 你是用 huan 提供的 docker 自己搭建的 token server 吗？我看到 [wechaty/wechaty#1985](https://github.com/wechaty/wechaty/issues/1985) 里有人遇到和你相同的问题

@huan  这好像需要你的协助

**Comment by echoboss** [comment]
> > @echoboss 你是用 huan 提供的 docker 自己搭建的 token server 吗？我看到 [wechaty/wechaty#1985](https://github.com/wechaty/wechaty/issues/1985) 里有人遇到和你相同的问题
> 
> @huan 这好像需要你的协助

需要我怎么做？

**Comment by huan** [comment]
@dchaofei yes, I'm morning it.

Please link all related issues with the reproduce steps and the log message to issue 1985, I'll try to solve it as soon as I get time to working on it.

**Comment by echoboss** [comment]
> @dchaofei yes, I'm morning it.
> 
> Please link all related issues with the reproduce steps and the log message to issue 1985, I'll try to solve it as soon as I get time to working on it.
